
version: "1"
metadata:
  template: true

steps:
  - name: Test and Build.
    commands:
      - npm install
    image: node:16-alpine
    pull: always
    ruleset:
      event: [ push, pull_request ]